### PR TITLE
changes the username block warning message to seem less scary

### PR DESCRIPTION
**Pull request by DatOneLefty**
on the suggestion https://scratch.mit.edu/discuss/topic/32509/ people didn't like the message that tells people that the project can know their username because it seemed scary. The change I made makes this message seem more safe to parents and the kids on scratch, the text I used was from https://scratch.mit.edu/discuss/topic/32509/?page=11 post 207

### CODE REVIEW

**Comment by liam4** [comment]
I think I agree with this; but it's important to note that this text has probably been translated into other languages as well, and that it would need to be changed in those translation files too!

**Comment by DatOneLefty** [comment]
i cant find the translation files in this repo, where are they for me to attempt to fix them?

**Comment by liam4** [comment]
Well, first off, they aren't in a GitHub repository, I believe, but more importantly – I highly doubt you can write in [all of the languages that Scratch works in](https://imgur.com/a/ZN17K) :)

**Comment by DatOneLefty** [comment]
thennnnn for now just english? It is the current majority so i think this PR could be done

**Comment by thisandagain** [comment]
Thanks for the contribution!

Scratch 2.0 is now in maintenance mode while the team focuses efforts on [Scratch 3.0](https://llk.github.io/scratch-gui). While critical issues will be addressed please note that any feature requests or minor issues will not be reviewed until 3.0 is released. Because of this, we will be closing this PR and only accepting patches to `scratch-flash` that resolve bugs labeled as `prio-critical`. 

If you are interested in contributing to Scratch 3.0 please take a look at the following repositories:
https://github.com/llk/scratch-gui
https://github.com/llk/scratch-blocks
https://github.com/llk/scratch-vm
https://github.com/llk/scratch-render
https://github.com/llk/scratch-audio

**Pull request closed without merging**
