### PR TITLE
Calculate MD5 if it's null

### PR DESCRIPTION
**Pull request by sclements**
Fixes both #781 and #750

### CODE REVIEW

**Comment by cwillisf** [comment]
:+1:

**Comment by 2jour** [comment]
I don't notice a fix for #750 though however i see an improvement for #781

**Comment by TheLogFather** [comment]
@2jour: how are you testing #750?
It looks better to me for https://scratch.mit.edu/projects/60472556/

**Comment by sclements** [comment]
I get 30fps rotating the clones in 3D and 8fps in 2D.

**Comment by TheLogFather** [comment]
Yes, 3D is much quicker.
But isn't the comparison (at least for now) for 2D against v437?
I get ~10fps with 438, but ~3 with 437...

**Pull request merged**
