### PR TITLE
No longer creating closures with every call to startEdgeTriggeredHats.

### PR DESCRIPTION
**Pull request by sclements**
This drastically improves performance with many clones.

### CODE REVIEW

**Comment by griffpatch** [comment]
This sounds exciting...  What is classed as a start edge triggered hat?

**Comment by cpseager** [comment]
@sclements 

     } else if ('whenSensorConnected' == hat.op) {

Is this section dead old 'picoboard' code no longer required at all?

**Comment by sclements** [comment]
@cpseager yes, we could probably remove that.
@griffpatch loudness, timer, and video motion hat blocks.

This method is called on all hat blocks for each sprite and clones.

**Comment by cwillisf** [comment]
:+1:

**Pull request merged**
