### PR TITLE
Renaming broadcasts (using right click menu)

### PR DESCRIPTION
**Pull request by AndersBillLinden**
Renaming broadcasts not allowing already existing broadcast messages.

### CODE REVIEW

**Comment by sclements** [comment]
Thanks for this effort @AndersBillLinden! Unfortunately getters are expensive in AS3 (http://stackoverflow.com/questions/11357427/better-working-with-setter-and-getter/11357513#11357513) and we should avoid using them in the interpreter. If you could remove them from this change I would be happy to add this feature.

**Comment by AndersBillLinden** [comment]
I stepped backwards one step now.

**Comment by AndersBillLinden** [comment]
I also removed getter+setter from the rename-lists branch which pull request is on https://github.com/LLK/scratch-flash/pull/640

**Comment by AndersBillLinden** [comment]
Would you please do the changes that are needed for satisfaction? You can add them to my changes or you can create them yourself. I dislike micro optimizations and prefer code readability. My motto is: If a performance drawback cannot be experienced by the end user, it is not a performance drawback. Still I want to contribute to the project. If all I would contribute with is to initiatiate an implementation of a certain functionality, I am satisfied contributing with that. The possibility of renaming lists is an example. That is something that the Scratch Community has asked for quite a while. I could have written a forum entry like everyone else to try push the change. Instead I did prove that it is not only possible but easily implemented, even as a project outsider. Use what you want with my changes. You can throw them away. You can add a zillion of micro optimzations in them. The only thing that is important to me is something happens.

**Comment by AndersBillLinden** [comment]
Are you sure the compiler will not optimize small functions and make them inline automatically?

**Comment by AndersBillLinden** [comment]
Is there some swf optimizer to use to get the performance you want?

**Comment by sclements** [comment]
No, we don't use a SWF optimizer. To see the performance bottlenecks we use Adobe Scout (https://creative.adobe.com/products/scout) which gives us detailed information about where the Flash player is spending its time.

**Comment by AndersBillLinden** [comment]
I must try it, maybe I change the branch soon.

**Comment by AndersBillLinden** [comment]
I have changed the branch, but there is another getter/setter pair that I want to know about. Should I rewrite that as well? Seems "messy" to do so.

**Comment by sclements** [comment]
This looks good now. We'll get it into the next release (436).

**Comment by AndersBillLinden** [comment]
:+1:

**Comment by sclements** [comment]
@2jour can you test this? I'll put it on a port.

**Pull request merged**
