### PR TITLE
When key released event block.

### PR DESCRIPTION
**Pull request by AndersBillLinden**
A block for key release events. If you want to create a game where objects are maneuvered with the keyboard, this would be appropriate so that they can stop when keys are released. Translations will also be needed.

### CODE REVIEW

**Comment by sclements** [comment]
Interesting idea. As I'm sure you know, the missing release hat can be worked around by using the <key X pressed> reporter.

**Comment by AndersBillLinden** [comment]
Maybe we should also add an option to key press to exclude repetitions, defaulting to not excluding those

**Comment by AndersBillLinden** [comment]
Ok, I have to admit that I do not know about the reporter! What is it?

**Comment by AndersBillLinden** [comment]
@sclements Ok, I have to admit I have not heard about the reporter, what is it? Also, would github send you a notice even if I did not prefix this comment with an at-sign and your name?

**Comment by sclements** [comment]
Yes, I received a notice even without being tagged. You can find the reporter in the Sensing block category. A reporter is a block that returns a value and can be used as an input for another block.

**Comment by AndersBillLinden** [comment]
Ah, yeah, now I see that reporter block. Maybe it makes sense to only have the key press block then. Or "an all keys are released" block in addition to the key press block. In either case, would it not be great to handle the key repetition "dilemma"?

**Pull request closed without merging**
