### PR TITLE
Don't play beyond the end of our buffer

### PR DESCRIPTION
**Pull request by sclements**
This should resolve an exception we're seeing in playBuffer (RangeError: Error #1125).

### CODE REVIEW

**Comment by rschamp** [comment]
LGTM, just curious how it can get into that state?

**Comment by sclements** [comment]
I don't know how it happens. Perhaps we'll have another bug someday for the sound editor where the sound doesn't play correctly. at least now there will be no exception to break the editor.

**Comment by 2jour** [comment]
Is this in production @sclements , @cwillisf ?

**Comment by cwillisf** [comment]
It looks to me like this went out with 439.2, yeah.

**Pull request merged**
