### PR TITLE
Custom reporters

### PR DESCRIPTION
**Pull request by nathan**
**Note**: Shane asked me to make this PR so we could discuss custom reporters. As I said earlier:

> I think it would be a cool feature to have, but the way I implemented it definitely wasn't the best.
> And we should think about the design a lot more carefully if we actually want it in Scratch.

That said, this is quite fun to play around with.

---

Rewrote the interpreter and added the user interface to support custom reporters.

screen shot 2014-05-11 at 14 36 56

screen shot 2014-05-11 at 12 58 21

### CODE REVIEW

**Comment by liam4** [comment]
*closes without reason* @sclements :P

**Comment by BookOwl** [comment]
PLEASE ADD THIS @thisandagain

**Comment by DrKat123** [comment]
Yeah

**Comment by DrKat123** [comment]
Yeah

**Comment by NoMod-Programming** [comment]
PLZ ADD THIS!!!

**Comment by thisandagain** [comment]
We will consider adding this in Scratch 3.0

**Pull request closed without merging**
