### PR TITLE
Add "any" to key press menu

### LINKED ISSUE #50: Add "any" to "when key pressed" (and <key pressed>) block
<a href="https://github.com/idreyn"></img></a> **Issue by [idreyn](https://github.com/idreyn)**
_Sunday Feb 02, 2014 at 19:46 GMT_
_Originally opened as https://github.com/LLK/scratch-flash-common/issues/896_

---

Add option to sense any key pressed
**Reporter:** Natalie Rusk
**Begin:** 2013-05-07
**Completed:** 0

### PR DESCRIPTION
**Pull request by nathan**
Fixes #50.

### CODE REVIEW

**Comment by AndersBillLinden** [comment]
Maybe adding a parameterless event block would be a good thing?

**Comment by sclements** [comment]
@ntlrsk this is old and I'm going to close it for now. If we come to a consensus on the design let's revisit.

**Comment by ealgase** [comment]
I personally support this, and it's important.

**Comment by sclements** [comment]
We're going to merge this soon :)

**Pull request merged**
