### PR TITLE
Fixed #257 segmentation bounding rect bug

### PR DESCRIPTION
**Pull request by bsb20**
-Prevent bottom and right edges of the bounding rect
    from going beyond the edges of the working area bitmap
    -Fixes #257 which was resulting in error 2030 (EOF) when
    the rectangle exceeded the edges of the bitmap

### CODE REVIEW

**Comment by bsb20** [comment]
Added some UI changes pursuant to the editor meeting this afternoon, then something weird happened with travis CI so I closed and reopened to trigger a new build.

**Comment by cwillisf** [comment]
For future reference, you can actually restart a Travis build directly from their UI by clicking this icon:
image

I didn't notice that button for an embarrassingly long time... I blame the pale-on-white color scheme.

**Comment by bsb20** [comment]
Ha, stackoverflow mentioned that button but I couldn't find it...

**Comment by cwillisf** [comment]
:+1: looks good to me

**Pull request merged**
