### PR TITLE
Improve framerate to 60fps instead of 30fps

### PR DESCRIPTION
**Pull request by DevanWolf**
It'll be nice if Scratch projects will run better in 60fps rather than the odd 30fps.

### CODE REVIEW

**Comment by bobbybee** [comment]
This is significantly more CPU intensive, no?

**Comment by liam4** [comment]
Bump, I suggest an option in the user preferences for this.

**Comment by bobbybee** [comment]
@liam4 Might fragment the community..

**Comment by sclements** [comment]
This change doesn't fit in the current Scratch design.

**Pull request closed without merging**
